/*
 * This source file was generated by the Gradle 'init' task
 */
package twitter;

import twitter.service.postService;
import twitter.service.userService;
import twitter.service.followService;
import java.sql.*;
import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        Connection con = null;

        userService userService = new userService();

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/twitter", "root", "1234");
            //con = DriverManager.getConnection("jdbc:mysql://localhost/twitter_clone", "root", "** Enter your password **");

            // need to change each local environment (change the password, connection url, and database name)

            while (true) {
                System.out.println("1. Sign Up");
                System.out.println("2. Log In");
                System.out.println("3. Delete accounnt");
                System.out.println("4. Exit");
                System.out.println();
                System.out.print("Choose an option: ");
                int choice = scanner.nextInt();
                scanner.nextLine(); // Consume newline

                switch (choice) {
                    case 1:
                        signUp(con, scanner, userService);
                        break;
                    case 2:
                        logIn(con, scanner, userService);
                        if(userService.currentUser != null){
                            System.out.println("Welcome, " + userService.currentUser.getName() + "!");
                            selectService(con, scanner, userService);
                        }
                        else{
                            System.out.println("Failed to login. Please check your credentials.");
                        }
                        break;
                    case 3:
                        deleteAccount(con, scanner, userService);
                        break;
                    case 4:
                        System.out.println("Exiting...");
                        return;
                    default:
                        System.out.println("Invalid option. Please try again.");
                }
            }


        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            try {
                if (con != null) con.close();
            } catch (SQLException e) {
                e.printStackTrace();
            }
            scanner.close();
        }
    }

    private static void deleteAccount(Connection con, Scanner scanner, userService userService) {
        System.out.print("Enter your name to confirm deletion: ");
        String name = scanner.nextLine();
        System.out.print("Enter your password: ");
        String password = scanner.nextLine();

        User userToDelete = new User(name, password);

        try {
            boolean isDeleted = userService.deleteAccount(con, userToDelete);
            if (isDeleted) {
                System.out.println("Account deleted successfully.");
            } else {
                System.out.println("Failed to delete account. Please check your credentials.");
            }
        } catch (SQLException e) {
            System.out.println("Error occurred: " + e.getMessage());
        }
    }

    private static void signUp(Connection con, Scanner scanner, userService userService) {
        System.out.print("Enter your name: ");
        String name = scanner.nextLine();
        System.out.print("Enter your password: ");
        String password = scanner.nextLine();
        System.out.print("Enter your phone number: ");
        String phoneNumber = scanner.nextLine();

        User newUser = new User(name, password, phoneNumber);
        try {
            userService.signup(con, newUser);
        } catch (SQLException e) {
            System.out.println("Error occurred: " + e.getMessage());
        }
    }

    private static void logIn(Connection con, Scanner scanner, userService userService) {
        System.out.print("Enter your name: ");
        String name = scanner.nextLine();
        System.out.print("Enter your password: ");
        String password = scanner.nextLine();

        User varifyUser = new User(name, password);

        try{
            userService.login(con, varifyUser);
        } catch (SQLException e) {
            System.out.println("Error occurred: " + e.getMessage());
        }
    }

    private static void selectService(Connection con, Scanner scanner, userService userService) {
        while (true) {
            System.out.println("1. Post");
            System.out.println("2. Follow");
            System.out.println("3. Tag Search");
            System.out.println("4. logout");
            System.out.println();
            System.out.print("Choose an option: ");
            int choice = scanner.nextInt();
            scanner.nextLine(); // Consume newline

            switch (choice) {
                case 1:
                    post(con, scanner, userService);
                    break;
                case 2:
                    follow(con, scanner, userService);
                    break;
                case 3:
                    //tag_search(con, scanner, currentUser); 임시로 정의해 두었습니다.
                    break;
                case 4:
                    System.out.println("Exiting...");
                    return;
                default:
                    System.out.println("Invalid option. Please try again.");
            }
        }
    }

    public static void post(Connection con, Scanner scanner, userService userService) {
        while(true) {
            System.out.println("1. Write a post");
            System.out.println("2. Delete a post");
            System.out.println("3. Search posts");
            System.out.println("4. Print all posts");
            System.out.println("5. Like a post");
            System.out.println("6. Back to previous menu");
            System.out.println();
            System.out.print("Choose an option: ");

            int choice = scanner.nextInt();
            scanner.nextLine(); // Consume newline

            switch (choice) {
                case 1:
                    System.out.print("Enter post content: ");
                    String content = scanner.nextLine();
                    postService.writePost(con, userService.currentUser, content); // 글 작성
                    break;
                case 2:
                    System.out.print("Enter post ID to delete: ");
                    int postIdToDelete = scanner.nextInt();
                    scanner.nextLine(); // Consume newline
                    postService.deletePost(con, userService.currentUser, postIdToDelete); // 글 삭제
                    break;
                case 3:
                    System.out.print("Enter search keyword: ");
                    String keyword = scanner.nextLine();
                    postService.searchPosts(con, keyword); // 게시글 검색
                    break;
                case 4:
                    postService.printAllPosts(con); // 모든 게시글 출력
                    break;
                case 5:
                    System.out.print("Enter post ID to like: ");
                    int postIdToLike = scanner.nextInt();
                    scanner.nextLine(); // Consume newline
                    postService.likePost(con, userService.currentUser, postIdToLike); // 게시글 좋아요
                    break;
                case 6:
                    System.out.println("Returning to previous menu...");
                    return; // 이전 메뉴로 돌아감
                default:
                    System.out.println("Invalid option. Please try again.");
            }
        }
    }


    public static void follow(Connection con, Scanner scanner, userService userService) {
        while(true) {
            System.out.println("1. Add to follow");
            System.out.println("2. List follower");
            System.out.println("3. List following");
            System.out.println("4. Back to previous menu");
            System.out.println();
            System.out.print("Choose an option: ");

            int choice = scanner.nextInt();
            scanner.nextLine(); // Consume newline

            switch (choice) {
                case 1:
                    System.out.print("Add to follow: ");
                    followService.follow(con, userService.currentUser); // 팔로우 추가
                    break;
                case 2:
                    System.out.print("List follower: ");
                    followService.seeFollower(con, userService.currentUser); // 팔로워 목록 확인
                    break;
                case 3:
                    System.out.print("List following: ");
                    followService.seeFollowing(con, userService.currentUser); // 팔로잉 목록 확인
                    break;
                case 4:
                    System.out.println("Returning to previous menu...");
                    return; // 이전 메뉴로 돌아감
                default:
                    System.out.println("Invalid option. Please try again.");
            }
        }
    }

    public static void tag_search(Connection con, Scanner scanner, User currentUser) {
    }




}
